### ISSUE TITLE
چندتا گزارش خطا مطرح شده در گروه

### ISSUE THREAD

**Issue by TiTAN-mu** [hiddify/HiddifyNG#13]
نسخه 1.5 نصب کردم، چندتا ایراد دیدم خواستم به اشتراک بزارم ❤️
1. برنامه نمیتونه به درستی کانفیگ مناسب پیدا کنه
2. کانفیگ هایی متصل میشه هم کند هست هم پینگ بالاتری نسبت به v2rayng داره بطوری که مثلا اگه یه کانفیگ تو v2ray پینگش 600 تو هیدیفای بین 2000 تا 4000 هزار
3. سابکریپشنی که اد کردم نمیشه از لیست پاک کرد

**Comment by TiTAN-mu** [comment]
خطای قادر به دریافت مجوز نیست اندروید 13 ورژن برنامه 1.5

**Comment by TiTAN-mu** [comment]
یه باگی که هست وقتی میزنی برنامه کانکت بشه 
نمیاد یه دور سابسکریبشن رو اپدیت کنه و این باعث میشه مثلا وقتی اخرین بار که وصل شده بودی و روی همراه اول بودی 
الان که با ایرانسل میخوای وصل بشی تو حالت CDN / Auto CDN باعث میشه سعی کنه با ای پی همراه اول وصل بشه و نتونه از ای پی تمیزی که مال ایرانسله استفاده کنه

**Comment by TiTAN-mu** [comment]
۱- عدم امکان حذف سابسکرایپشن‌ها
۲- عدم پشتیبانی از فرمت سابسکرایب کلش YAML «میدونم دیگه از هسته کلش استفاده نمیشه ولی اگر کانفیگارو اضافه کنه عالی میشه»
۳- فارسی سازی متن ارورها «حالا که کل برنامه فارسی شده ارورها هم ترجمه کنید»

**Comment by TiTAN-mu** [comment]
مشکل سورت کردن تو ورژن ۱.۵ حل شد.
ولس مشکل عدم نوتیفکیشن تو اندروید من که ۱۳ هست هنوز وجود داره و کلا نوتیف نمیاد اون بالا.برای قطع و وصل هم حتمی باید برگردی تو اپ خاموش کنی چون تو نوار بالا نیست که بکشی پایین و اف کنی

**Comment by TiTAN-mu** [comment]
دربرنامه هنگام انتخاب گزینه Advance برنامه کرش شده و از برنامه خارج میشود

**Comment by TiTAN-mu** [comment]
برا بار اول که نصب میکنی و باز میکنی کرش میکنه و کلا گوشی هنگ میکنه یبار کامل ببندی و باز کنی درست میشه
آندروید ۱۳

**Comment by hiddify1** [comment]
لطفا توی ایشوهای جدا بذارید که وقتی هرکدوم حل میشه بزنم حل شد
