### ISSUE TITLE
بیلد‌های مخصوص معماری‌های مختلف

### ISSUE THREAD

**Issue by Alex-STT** [hiddify/HiddifyNG#17]
سلام.

من گوشیم قدیمیه که جای زیادی نداره... به خاطر اگه بتونم نسخه‌های مخصوص معماری گوشیم رو نصب می‌کنم (مثل معماری `armeabi-v7a`) که جای کمتری روی گوشیم بگیره. (برای مثال تفاوت در مورد نسخه‌ی آخر v2rayNG تفاوت ۱۷.۱ مگابایت و ۴۵.۷ مگابایته، که بیشتر از ۲.۵ برابر می‌شه...)

شما برای پروژه‌ی HiddifyClashAndroid این کارو انجام می‌دید، و v2rayNG هم این کارو انجام می‌ده. اگه می‌شه لطف کنید و برای این پروژه هم این کارو انجام بدید که بتونیم ازش استفاده کنیم.

(در ضمن، اگه نسخه‌های `armeabi-v7a` و `arm64-v8a` به پنل هم اضافه بشن، خیلی عالی می‌شه، که هر دفعه مجبور نباشیم بیایم توی گیت‌هاب دنبالشون بگردیم.)

ممنون بابت پروژه‌ی بسیار خوبتون.

**Comment by hiddify1** [comment]
به زودی برای گوگل پلی منتشر میکنیم دیگه این مشکل رفع میشه

**Comment by vafaaee** [comment]
> به زودی برای گوگل پلی منتشر میکنیم دیگه این مشکل رفع میشه

البته این رو هم در نظر داشته باشید که گوشی های زیادی هستن گوگل پلی ندارن🤦‍♂️ بعلاوه در شرایط فیلترینگ امکان دسترسی برای همه به گوگل پلی وجود نداره 🤦‍♂️🤦‍♂️

**Comment by hiddify1** [comment]
میتونید اکشن گیت هابشو بنویسید؟
