### ISSUE TITLE
پروکسی اپ ها

### ISSUE THREAD

**Issue by mmdjvdad** [hiddify/HiddifyNG#18]
در پروکسی هر اپ، فقط برنامه های سیستم رو میاره و برنامه های نصب شده توسط کاربر نمایش داده نمیشه
![Screenshot_2023-05-03-15-16-59-330_ang hiddify com](https://user-images.githubusercontent.com/122828400/235908094-ce736679-ec4d-464d-bbb6-0d6c4472e846.jpg)

**Comment by vafaaee** [comment]
ضمنا پروکسی اپ ها بدرستی عمل نمیکنه، مشکل داره

**Comment by hiddify1** [comment]
اضافه شد
