### ISSUE TITLE
مشکل اندروید 13

### ISSUE THREAD

**Issue by vafaaee** [hiddify/HiddifyNG#25]
عزیزان دل
مشکل اندروید 13 همچنان برقراره
![IMG_20230504_012527_485](https://user-images.githubusercontent.com/50930366/236059009-11de5310-0b09-42d8-9515-954af6e89918.jpg)
![IMG_20230504_012527_658](https://user-images.githubusercontent.com/50930366/236059048-de2f6b4e-340c-4540-b9bc-d74cf08d8cce.jpg)
فقط در حالت دستی کانکت میشه
لودبالانس و هوشمند همون failure رو میده

**Comment by vafaaee** [comment]
روی اندروید 12 نوت 9 شیاومی همین ارور دوباره

**Comment by hiddify1** [comment]
logcat 
چی میده؟

**Comment by saeed-af** [comment]
> logcat چی میده؟

درود
![Screenshot_2023-05-05-09-10-55-711_ang hiddify com](https://user-images.githubusercontent.com/132642231/236384735-41c06046-a1b8-4920-9a46-defbd0023229.jpg)

**Comment by saeed-af** [comment]
> logcat چی میده؟

درود .
--------- beginning of main
Main ViewModel is cleared
9972): loading core config
9972): Preparing Domain: www.snapp.ir:80
9972): infra/conf/serial: failed to parse json config > infra/conf: unknown cipher method: �m
9972): go.Universe$proxyerror: infra/conf/serial: failed to parse json config > infra/conf: unknown cipher method: �m
9972): Prepare Result:
9972):Domain: www.snapp.ir
9972):Port: 80
9972):IPs: [86.104.35.19]
9972): loading core config
9972): Preparing Domain: www.snapp.ir:80
9972): Prepare Result:
9972):Domain: www.snapp.ir
9972):Port: 80
9972):IPs: [86.104.35.19]
9972): infra/conf/serial: failed to parse json config > infra/conf: unknown cipher method: �m
9972): go.Universe$proxyerror: infra/conf/serial: failed to parse json config > infra/conf: unknown cipher method: �m
9972): loading core config
9972): Preparing Domain: www.snapp.ir:80
9972): infra/conf/serial: failed to parse json config > infra/conf: unknown cipher method: �m
9972): go.Universe$proxyerror: infra/conf/serial: failed to parse json config > infra/conf: unknown cipher method: �m
9972): Prepare Result:
9972):Domain: www.snapp.ir
9972):Port: 80
9972):IPs: [86.104.35.19]
9972): Shutting down VM
--------- beginning of crash
9972): FATAL EXCEPTION: main
9972): Process: ang.hiddify.com:RunSoLibV2RayDaemon, PID: 9972
9972): android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e6b3df7 u0 ang.hiddify.com/com.v2ray.ang.service.V2RayVpnService}
9972): 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2103)
9972): 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2074)
9972): 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
9972): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2339)
9972): 	at android.os.Handler.dispatchMessage(Handler.java:106)
9972): 	at android.os.Looper.loopOnce(Looper.java:211)
9972): 	at android.os.Looper.loop(Looper.java:300)
9972): 	at android.app.ActivityThread.main(ActivityThread.java:8152)
9972): 	at java.lang.reflect.Method.invoke(Native Method)
9972): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
9972): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by hiddify1** [comment]
مشکل از shadowtls هست غیرفعالش کنید فعلا
