### ISSUE TITLE
نبود لیست برنامه ها در per app proxy

### ISSUE THREAD

**Issue by mostafacpr** [hiddify/HiddifyNG#27]
سلام خسته نباشید
برنامه هایی که تو گوشی نصب شده در لیست per app proxy برای جدا کردن ترافیک وجود ندارد 
با تشکر

**Comment by mcuteangel** [comment]
درسته، حتی اکثر برنامه های سیستمی هم نمیاد تو لیست

**Comment by hiddify1** [comment]
اضافه شد

**Comment by mostafacpr** [comment]
ممنون از زحمات دلسوزانه شما💯💙💚

**Comment by mostafacpr** [comment]
ممنون از زحمات دلسوزانه شما💯💙💚
