### ISSUE TITLE
عدم اتصال کانفیگ از سایر پنلها

### ISSUE THREAD

**Issue by mlm1102003** [hiddify/HiddifyNG#29]
سلام
این برنامه فقط برای پنل هیدیفای هست ؟

کانفیگ از پنل دیگه که روی v2rayng وصل میشه وقتی این برنامه میذارم لیست میاره پینگ هم میده منتها چیزی باز نمیکنه

**Comment by hiddify1** [comment]
نسخه گوگل پلی مشکل داره صبر کنید تا گوگل نسخه جدید را تایید کنه

خیر روی همه پنل ها کار میکنه
