### ISSUE TITLE
پیشنهاد میشه وقتی اولین کانفیگ برای بار اول به نرم افزار اضافه شد به صورت پیشفرض انتخاب بشه و تازه سازی هم بشه تا اطلاعاتش بیاد

### ISSUE THREAD

**Issue by TiTAN-mu** [hiddify/HiddifyNG#34]
پیشنهاد میشه وقتی اولین کانفیگ برای بار اول به نرم افزار اضافه شد به صورت پیشفرض انتخاب بشه و تازه سازی هم بشه تا اطلاعاتش بیاد

**Comment by hiddify1** [comment]
نسخه گوگل پلی مشکل داره صبر کنید تا گوگل نسخه جدید را تایید کنه
