### ISSUE TITLE
باگ تعداد روز سابسکریپشن پنلهای دیگر

### ISSUE THREAD

**Issue by Amirbazz** [hiddify/HiddifyNG#63]
بعد از وارد کردن لینک سابسکریپشن تو تعداد روز نرم افزار اشتباه محاسبه میکنه 
صفحه اصلی درست محاسبه میشه اما تو این قسمت نرم افزار که محیطی شبیه v2rang داره اشتباه مینویسه

![IMG_20230508_154717.jpg](https://user-images.githubusercontent.com/120129395/236822048-7ab1636e-61ef-44dc-859f-1acfb967729e.jpg)

**Comment by hiddify1** [comment]
رفع شد
