### ISSUE TITLE
DNS/DoH and SNI

### ISSUE THREAD

**Issue by alidxdydz** [hiddify/HiddifyNG#69]
سلام،
بنظرتون این بحث SNI بدون DoH اصلا اهمیت داره یا نه؟ من فکر میکنم تا مشکل DNS حل نشه اصلا SNI مهم نیست.
در ضمن این GoodbyeDPI تکینک‌های مختلفی برا دور زدن DPI داره و هر کدوم روی یه ISP نتیجه میده.
مثلا تکنیک دور زدن DPI روی کلاینت RethinkDNS که داخلش یه DoH ست شده، روی ایرانسل عالی کار میکنه.
شما باید اینا رو بیرون بکشید و برا هر ISP یه تکنیک دور زدن DPI داشته باشیم.
ایشون رو ویندوز این کارو خیلی عال انجام داده.

[SecureDNSClient](https://github.com/msasanmh/SecureDNSClient)

**Comment by karimi12** [comment]
بحث SNI و  DOH دیتا موضوع متفاوت هستند 

البته خوب DOH  اضافه بشه و اینکه اگر دامینی چندتا ای پی داشت دونه دونه ای پی ها تست بشوند اما تا جایی که من اطلاع دارم این دوتا بحثش با هم متفاوت هست

**Comment by alidxdydz** [comment]
> بحث SNI و  DOH دیتا موضوع متفاوت هستند 
> 
> البته خوب DOH  اضافه بشه و اینکه اگر دامینی چندتا ای پی داشت دونه دونه ای پی ها تست بشوند اما تا جایی که من اطلاع دارم این دوتا بحثش با هم متفاوت هست

درسته متفاوتن. من میگم اگه DNS درست کار نکنه اصلا فیلتر شدن من به مرحله SNI نمیکشه.
داخل cmd یبار آدرس youtube.com رو با Plain DNS و یبار DoH پینگ بگیر.
